version: 0.2

env:
  variables:
    venv_name: crud_ops_env
  secrets-manager:
    BQkey: "arn:aws:secretsmanager:us-east-2:511772300310:secret:ggkey-E2ay7B"

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      python: 3.9
    commands:
      - echo $BQkey["ggkey"]
      - python3 -m venv $venv_name
      - source ./$venv_name/bin/activate
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - mkdir test-reports
  build:
    commands:
      - source ./$venv_name/bin/activate
      - python3 unit_test.py --google_key $BQkey
