version: 0.2

env:
  variables:
    venv_name: crud_ops_env
  secrets-manager:
    BQkey: arn:aws:secretsmanager:us-east-2:511772300310:secret:bigquery_proj_key-g9VBjR

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      python: 3.9
    commands:
      - echo $BQkey
      - pip3 install venv
      - python3 -m venv $venv_name
      - source ./$venv_name/bin/activate
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - mkdir test-reports
