name: Azure Python 3.9
VENV = crud_ops_env
PYTHON = $(VENV)/bin/python3
PIP = $(VENV)/bin/pip
GOOGLE_CRED_FILE= '/Users/umairk/Downloads/ukhushn-proj2-kkey.json'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: setup python 3.9
      run: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install dependencies
      $(VENV)/bin/activate: requirements.txt
        python3 -m venv $(VENV)
        $(PIP) install -r requirements.txt

    - name: Run check
      run: $(VENV)/bin/activate
        $(PYTHON) unit_test.py --google_cred_path $(GOOGLE_CRED_FILE)
